POST http://localhost:3333/subscription
Content-Type: application/json

{
  "name": "Indicado  2",
  "email": "id2@gmail.com",
  "referrer": "632b0087-804f-4b8d-9f92-1b2b7df096dc"
}

###
GET http://localhost:3333/invites/632b0087-804f-4b8d-9f92-1b2b7df096dc

###
GET http://localhost:3333/subscribers/632b0087-804f-4b8d-9f92-1b2b7df096dc/ranking/clicks

###
GET http://localhost:3333/subscribers/632b0087-804f-4b8d-9f92-1b2b7df096dc/ranking/count

###
GET http://localhost:3333/subscribers/632b0087-804f-4b8d-9f92-1b2b7df096dc/ranking/position