POST http://localhost:3333/subscription
Content-Type: application/json

{
  "name": "Indicado  Convidado",
  "email": "uc@gmail.com",
  "referrer": "b703a0fd-d4da-420e-b609-242aa449d28e"
}

###
GET http://localhost:3333/invites/632b0087-804f-4b8d-9f92-1b2b7df096dc

###
GET http://localhost:3333/subscribers/632b0087-804f-4b8d-9f92-1b2b7df096dc/ranking/clicks

###
GET http://localhost:3333/subscribers/632b0087-804f-4b8d-9f92-1b2b7df096dc/ranking/count

###
GET http://localhost:3333/subscribers/632b0087-804f-4b8d-9f92-1b2b7df096dc/ranking/position

###
GET http://localhost:3333/ranking

###
POST http://localhost:3333/messages
Content-Type: application/json

{
  "message": "Quais os e-mails dos usuários cadastrados em minha aplicação?"
}